server:
  http_listen_port: 9080
  grpc_listen_port: 0

positions:
  filename: /var/lib/promtail/positions.yaml

clients:
  - url: http://loki:3100/loki/api/v1/push

wal:
  enabled: true
  dir: /var/lib/promtail/wal

scrape_configs:
  - job_name: docker
    docker_sd_configs:
      - host: unix:///var/run/docker.sock
        refresh_interval: 5s
        filters:
          - name: network
            values: [poupe-ai-network]
    relabel_configs:
      - source_labels: ['__meta_docker_container_label_com_docker_compose_service']
        target_label: 'service_name'
    
    pipeline_stages:
      - json:
          expressions:
            level: level
            event_type: event_type
          drop_malformed: true
            
      - labels:
          level:
          event_type: